apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmdb.fullname" . }}-cmdb-ui
  labels:
    {{- include "cmdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cmdb.selectorLabels" . | nindent 4 }}
